name: flutter_netflix
description: "A new Flutter project."

publish_to: 'none' # Retirer cette ligne si tu souhaites publier sur pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.14.1
  lottie: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: true
  image_path: "assets/images/symbol.png"
  background_color: "#000000"
  min_sdk_android: 21

flutter_native_splash:
  color: "#000000" # Couleur de fond pour la splash screen
  image: "assets/images/symbol.png" # Chemin vers ton image de splash screen
  android_12: 
    image: "assets/images/symbol.png"


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lotties/
